generic_hw_control_loop:
  loop_hz: 100
  cycle_time_error_threshold: 0.03

# Settings for ros_control hardware interface
hardware_interface:
  sim_control_mode: 0
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
